---
  - name: "install nginx repo"
    ansible.builtin.yum_repository:
      name: "nginx"
      description: install repo
      baseurl: https://nginx.org/packages/centos/$releasever/$basearch/
      gpgcheck: no
      enabled: true

    notify:
      - Update 
  - name: Install nginx
    ansible.builtin.yum:
      name: nginx
      state: present
      
    notify: Start nginx
  - name: Enable nginx
    ansible.builtin.systemd:
      name: nginx
      enabled: true  
    
  - name: Change port nginx
    ansible.builtin.template:
      src: ../templates/default.conf.j2
      dest: /etc/nginx/conf.d/default.conf 
    notify: Reload nginx

    
        
    